- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hours
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Detective
  - Cryogenics
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  alternateTitles:
  - DetectiveTitleInvestigator
  - DetectiveTitleExpert
  - DetectiveTitleAnalist


- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    gloves: ClothingHandsGlovesForensic
    ears: ClothingHeadsetAltSecurityRegular # Goobstation
    belt: ClothingBeltHolsterFilled
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
    - SecHypo # Goobstation

- type: jobAlternateTitle
  id: DetectiveTitleInvestigator
  name: job-name-alt-detective-investigator

- type: jobAlternateTitle
  id: DetectiveTitleExpert
  name: job-name-alt-detective-expert

- type: jobAlternateTitle
  id: DetectiveTitleAnalist
  name: job-name-alt-detective-analist
