- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 10800 #3 hrs
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hrs
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  alternateTitles:
  - HeadOfSecurityTitleGuard
  - HeadOfSecurityTitleSheriff
  - HeadOfSecurityTitleChief
  - HeadOfSecurityTitleDirector


- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
    - SecHypo # Goobstation

- type: jobAlternateTitle
  id: HeadOfSecurityTitleGuard
  name: job-name-alt-hos-guard

- type: jobAlternateTitle
  id: HeadOfSecurityTitleSheriff
  name: job-name-alt-hos-sheriff

- type: jobAlternateTitle
  id: HeadOfSecurityTitleChief
  name: job-name-alt-hos-chief

- type: jobAlternateTitle
  id: HeadOfSecurityTitleDirector
  name: job-name-alt-hos-director
