- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 #10 hrs
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  alternateTitles:
  - SecurityOfficerTitleInstructor
  - SecurityOfficerTitleGuard
  - SecurityOfficerTitleVigilante


- type: startingGear
  id: SecurityOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltSecurityRegular # Goobstation
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
    - SecHypo # Goobstation

- type: jobAlternateTitle
  id: SecurityOfficerTitleInstructor
  name: job-name-alt-secoff-instructor

- type: jobAlternateTitle
  id: SecurityOfficerTitleGuard
  name: job-name-alt-secoff-guard

- type: jobAlternateTitle
  id: SecurityOfficerTitleVigilante
  name: job-name-alt-secoff-vigilante
