- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 #10 hrs
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  alternateTitles:
  - WardenTitleClerk
  - WardenTitleChief
  - WardenTitleDispacher
  - WardenTitleManager


- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetAltWarden # Goobstation
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
    - SecHypo # Goobstation

- type: jobAlternateTitle
  id: WardenTitleClerk
  name: job-name-alt-warden-clerk

- type: jobAlternateTitle
  id: WardenTitleChief
  name: job-name-alt-warden-chief

- type: jobAlternateTitle
  id: WardenTitleDispacher
  name: job-name-alt-warden-dispacher

- type: jobAlternateTitle
  id: WardenTitleManager
  name: job-name-alt-warden-manager
