- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Amber
  - Bagel
  - Box
  - Cluster
  #- Cog # Goobstation - cog is broken
  - Core
  - Fland
  - Gate
  #- Loop #Gabystation - mapa ruim
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  #- Reach # Gabystation - mapa ruim
  #- Train # Gabystation - mapa ruim
  - FlandHighPop
  - OasisHighPop
  - Barratry # Goobstation - Re-add barratry
  - Kettle # Goobstation - Re-add kettle (before it was gemini!)
  - Gamma # Gabystation
  - Gax # Gabystation
  - Falcon #Gabystation
