- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  startingGear: ReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  alternateTitles:
  - ReporterTitleAnchor
  - ReporterTitleInterviewer
  - ReporterTitleTv


- type: startingGear
  id: ReporterGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ReporterPDA
    ears: ClothingHeadsetService
  storage: # DeltaV: Give reporters tape recording equipment
    back:
    - TapeRecorder
    - CassetteTape
    - CassetteTape

- type: jobAlternateTitle
  id: ReporterTitleAnchor
  name: job-name-alt-reporter-anchor

- type: jobAlternateTitle
  id: ReporterTitleInterviewer
  name: job-name-alt-reporter-interviewer

- type: jobAlternateTitle
  id: ReporterTitleTv
  name: job-name-alt-reporter-tv
