- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage
  - External # goobstation
  alternateTitles:
  - CargoTechnitianTitleMail
  - CargoTechnitianTitlePilot
  - CargoTechnitianTitleStorage
  - CargoTechnitianTitleRessuplier

- type: startingGear
  id: CargoTechGear
  equipment:
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: CargoTechnitianTitleMail
  name: job-name-alt-cargotech-mail

- type: jobAlternateTitle
  id: CargoTechnitianTitlePilot
  name: job-name-alt-cargotech-pilot

- type: jobAlternateTitle
  id: CargoTechnitianTitleStorage
  name: job-name-alt-cargotech-storage

- type: jobAlternateTitle
  id: CargoTechnitianTitleRessuplier
  name: job-name-alt-cargotech-ressuplier
