- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 10800 #3 hrs
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hours
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  - External # goobstation
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  alternateTitles:
  - QuarterMasterTitleChief
  - QuarterMasterTitleAccountant
  - QuarterMasterTitleSupervisor
  - QuarterMasterTitleManager

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetAltCargo # Goobstation
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation

- type: jobAlternateTitle
  id: QuarterMasterTitleChief
  name: job-name-alt-qm-chief

- type: jobAlternateTitle
  id: QuarterMasterTitleAccountant
  name: job-name-alt-qm-accountant

- type: jobAlternateTitle
  id: QuarterMasterTitleSupervisor
  name: job-name-alt-qm-supervisor

- type: jobAlternateTitle
  id: QuarterMasterTitleManager
  name: job-name-alt-qm-manager
