using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Content.Shared.MOTD;
using Robust.Shared.Network;
using Content.Client.Message;
using Robust.Shared.Localization;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyBuletin : Control
{
    [Dependency] private readonly IClientNetManager _netManager = default!;

    public Button? ShowMOTDButton = null;

    public LobbyBuletin()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        CloseButton.OnPressed += CloseButtonPressed;
    }

    public void RefreshContent(MsgMOTD msg)
    {
        MOTDLabel.SetMessage(msg.MOTD, null, Color.Goldenrod);
        this.Visible = true;
        ShowMOTDButton!.Visible = false;
    }

    public void RequestMOTD()
    {
        _netManager.ClientSendMessage(new MsgMOTDRequest());
    }

    private void CloseButtonPressed(BaseButton.ButtonEventArgs args)
    {
        this.Visible = false;
        ShowMOTDButton!.Visible = true;
    }
}
