- type: job
  id: Botanist
  name: job-name-botanist
  description: job-description-botanist
  playTimeTracker: JobBotanist
  startingGear: BotanistGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Hydroponics
  extendedAccess:
  - Kitchen
  - Bar
  alternateTitles:
  - BotanistTitleGardener
  - BotanistTitleTech
  - BotanistTitleFarmer

- type: startingGear
  id: BotanistGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltPlantFilled
  #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: BotanistTitleGardener
  name: job-name-alt-botanist-gardener

- type: jobAlternateTitle
  id: BotanistTitleTech
  name: job-name-alt-botanist-tech

- type: jobAlternateTitle
  id: BotanistTitleFarmer
  name: job-name-alt-botanist-farmer

