- type: job
  id: Clown
  name: job-name-clown
  description: job-description-clown
  playTimeTracker: JobClown
  startingGear: ClownGear
  icon: "JobIconClown"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: Clumsy
      gunShootFailDamage:
        types: #literally just picked semi random valus. i tested this once and tweaked it.
          Blunt: 5
          Piercing: 4
        groups:
          Burn: 3
    - type: SleepEmitSound
      snore: /Audio/Voice/Misc/silly_snore.ogg
      interval: 10
  - !type:AddImplantSpecial
    implants: [ SadTromboneImplant ]
  alternateTitles:
  - ClownTitleJester
  - ClownTitleMaster
  - ClownTitleChief
  - ClownTitleComedian
  - ClownTitleActor
  - ClownTitleActress


- type: startingGear
  id: ClownGear
  equipment:
    mask: ClothingMaskClown
    pocket1: BikeHorn
    pocket2: ClownRecorder
    id: ClownPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampClown
    - CrayonRainbow

- type: jobAlternateTitle
  id: ClownTitleJester
  name: job-name-alt-clown-jester

- type: jobAlternateTitle
  id: ClownTitleMaster
  name: job-name-alt-clown-master

- type: jobAlternateTitle
  id: ClownTitleChief
  name: job-name-alt-clown-chief

- type: jobAlternateTitle
  id: ClownTitleComedian
  name: job-name-alt-clown-comedian

- type: jobAlternateTitle
  id: ClownTitleActor
  name: job-name-alt-clown-actor

- type: jobAlternateTitle
  id: ClownTitleActress
  name: job-name-alt-clown-actress

