- type: job
  id: Librarian
  name: job-name-librarian
  description: job-description-librarian
  playTimeTracker: JobLibrarian
  startingGear: LibrarianGear
  icon: "JobIconLibrarian"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  alternateTitles:
  - LibrarianTitleWriter
  - LibrarianTitleEvent
  - LibrarianTitleTech


- type: startingGear
  id: LibrarianGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LibrarianPDA
    ears: ClothingHeadsetService
    pocket1: d20Dice
    pocket2: HandLabeler # for making named bestsellers
  storage:
    back:
    - BookRandom

- type: jobAlternateTitle
  id: LibrarianTitleWriter
  name: job-name-alt-librarian-writer

- type: jobAlternateTitle
  id: LibrarianTitleEvent
  name: job-name-alt-librarian-event

- type: jobAlternateTitle
  id: LibrarianTitleTech
  name: job-name-alt-librarian-tech

