- type: job
  id: Mime
  name: job-name-mime
  description: job-description-mime
  playTimeTracker: JobMime
  startingGear: MimeGear
  icon: "JobIconMime"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: MimePowers
    - type: FrenchAccent
  alternateTitles:
  - MimeTitleFrench
  - MimeTitleComedian
  - MimeTitlePretend
  - MimeTitleExpressionist
  - MimeTitleActor
  - MimeTitleActress
  - MimeTitleChaplin


- type: startingGear
  id: MimeGear
  equipment:
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesColorWhite
    pocket1: CrayonMime
    pocket2: Paper
    id: MimePDA
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampMime

- type: entity
  id: ActionMimeInvisibleWall
  name: Create Invisible Wall
  description: Create an invisible wall in front of you, if placeable there.
  components:
  - type: InstantAction
    priority: -1
    useDelay: 30
    icon:
      sprite: Structures/Walls/solid.rsi
      state: full
    event: !type:InvisibleWallActionEvent

- type: jobAlternateTitle
  id: MimeTitleFrench
  name: job-name-alt-mime-french

- type: jobAlternateTitle
  id: MimeTitleComedian
  name: job-name-alt-mime-comedian

- type: jobAlternateTitle
  id: MimeTitlePretend
  name: job-name-alt-mime-pretend

- type: jobAlternateTitle
  id: MimeTitleExpressionist
  name: job-name-alt-mime-expressionist

- type: jobAlternateTitle
  id: MimeTitleActor
  name: job-name-alt-mime-actor

- type: jobAlternateTitle
  id: MimeTitleActress
  name: job-name-alt-mime-actress

- type: jobAlternateTitle
  id: MimeTitleChaplin
  name: job-name-alt-mime-chaplin

