- type: job
  id: Musician
  name: job-name-musician
  description: job-description-musician
  playTimeTracker: JobMusician
  startingGear: MusicianGear
  icon: "JobIconMusician"
  supervisors: job-supervisors-hire
  access:
  - Maintenance # TODO Remove maint access for all gimmick jobs once access work is completed
  - Theatre
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MikuDay
    prototype: BoxPerformer
  alternateTitles:
  - MusicianTitleStar
  - MusicianTitlePianist
  - MusicianTitleMulti
  - MusicianTitleSinger
  - MusicianTitleAcordeon


- type: startingGear
  id: MusicianGear
  equipment:
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesBootsLaceup
    id: MusicianPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: MusicianTitleStar
  name: job-name-alt-musician-star

- type: jobAlternateTitle
  id: MusicianTitlePianist
  name: job-name-alt-musician-pianist

- type: jobAlternateTitle
  id: MusicianTitleMulti
  name: job-name-alt-musician-multi

- type: jobAlternateTitle
  id: MusicianTitleSinger
  name: job-name-alt-musician-singer

- type: jobAlternateTitle
  id: MusicianTitleAcordeon
  name: job-name-alt-musician-acordeon

