- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  description: job-description-serviceworker
  playTimeTracker: JobServiceWorker
  startingGear: ServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-service
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen
  extendedAccess:
  - Hydroponics
  alternateTitles:
  - ServiceWorkerTitleWorker
  - ServiceWorkerTitleAssistant
  - ServiceWorkerTitleWaiter


- type: startingGear
  id: ServiceWorkerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: ServiceWorkerTitleWorker
  name: job-name-alt-serviceworker-worker

- type: jobAlternateTitle
  id: ServiceWorkerTitleAssistant
  name: job-name-alt-serviceworker-assistant

- type: jobAlternateTitle
  id: ServiceWorkerTitleWaiter
  name: job-name-alt-serviceworker-waiter
