- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 36000 #10 hrs
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  - External # goobstation
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  alternateTitles:
  - ResearchDirectorTitleChief
  - ResearchDirectorTitleManager
  - ResearchDirectorTitleSupervisor


- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetAltScience # Goobstation
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation

- type: jobAlternateTitle
  id: ResearchDirectorTitleChief
  name: job-name-alt-rd-chief

- type: jobAlternateTitle
  id: ResearchDirectorTitleManager
  name: job-name-alt-rd-manager

- type: jobAlternateTitle
  id: ResearchDirectorTitleSupervisor
  name: job-name-alt-rd-supervisor
